name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          cache: 'maven'
          distribution: 'zulu'
      - name: Install
        run: |
          mvn -ntp -pl 'flink-test-utils-parent/flink-connector-test-utils,flink-connectors/flink-connector-pulsar,flink-connectors/flink-sql-connector-pulsar' clean install -DskipTests
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "flink-connectors/flink-connector-pulsar/target/flink-connector-pulsar-*.jar,flink-connectors/flink-sql-connector-pulsar/target/flink-sql-connector-pulsar-*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
